"""Capture the screens as PNGs, and write down what took them.

The captures live beside the tests and are regenerated by running them, so they cannot
drift away from the code the way a screenshot pasted into a pull request does. Rendering
is deterministic -- fixed logical frame, fixed palette, bitmap font, no clock, seeded
state -- so a rerun on the same machine produces the same bytes.

The terminal capture is taken from a state the test assembled and is stamped with a
banner that says so. The client cannot reach an outcome on its own in this build, and a
screenshot that did not say which kind it was would be a claim the code does not support.
"""

from __future__ import annotations

import platform
import sys
from pathlib import Path

import pygame
from battle_city_client import Action, PlayerIntent, theme
from battle_city_client.shell import ClientShell, Screen
from battle_city_client.stage_adapter import bundled_stage_catalog
from battle_city_sim import DEFAULT_RULES, Direction, RunOutcome
from client_helpers import (
    SCREENSHOT_DIR,
    capture,
    finished_session,
    make_shell,
    observed,
)

CAPTURE_SCALE = 2
STAGE_TICKS = 150


def _bundled_shell() -> ClientShell:
    return ClientShell(catalog=bundled_stage_catalog())


def _played_shell() -> ClientShell:
    """Classic stage 1, driven with the same intents a keyboard produces."""
    shell = _bundled_shell()
    shell.handle(Action.UI_CONFIRM)
    shell.handle(Action.UI_CONFIRM)
    shell.advance(STAGE_TICKS, PlayerIntent(direction=Direction.DOWN, fire=True))
    return shell


def test_capture_the_main_menu() -> None:
    path = capture(_bundled_shell(), "01-main-menu", scale=CAPTURE_SCALE)
    assert path.stat().st_size > 0


def test_capture_stage_selection() -> None:
    shell = _bundled_shell()
    shell.handle(Action.UI_CONFIRM)
    assert observed(shell.screen) is Screen.STAGE_SELECT
    assert capture(shell, "02-stage-select", scale=CAPTURE_SCALE).stat().st_size > 0


def test_capture_the_controls_screen() -> None:
    shell = _bundled_shell()
    shell.handle(Action.UI_DOWN)
    shell.handle(Action.UI_CONFIRM)
    assert observed(shell.screen) is Screen.CONTROLS
    assert capture(shell, "03-controls", scale=CAPTURE_SCALE).stat().st_size > 0


def test_capture_an_active_stage_with_its_hud() -> None:
    shell = _played_shell()
    assert observed(shell.screen) is Screen.PLAYING
    assert shell.session is not None
    assert shell.session.state.tick == STAGE_TICKS
    assert capture(shell, "04-stage-and-hud", scale=CAPTURE_SCALE).stat().st_size > 0


def test_capture_the_pause_screen() -> None:
    shell = _played_shell()
    shell.handle(Action.TOGGLE_PAUSE)
    assert observed(shell.screen) is Screen.PAUSED
    assert capture(shell, "05-pause", scale=CAPTURE_SCALE).stat().st_size > 0


def test_capture_the_injected_terminal_screen() -> None:
    """Labelled in the filename and stamped on the image: this state was assembled."""
    shell = _bundled_shell()
    shell.open_session(
        finished_session(RunOutcome.BASE_DESTROYED, stage=shell.catalog[0].stage, ticks=90)
    )
    assert observed(shell.screen) is Screen.RUN_OVER
    path = capture(shell, "06-run-over-TEST-FIXTURE", scale=CAPTURE_SCALE, fixture=True)
    assert path.stat().st_size > 0


def test_write_the_capture_notes() -> None:
    """Record what produced the images, since a screenshot without them proves little."""
    driver = pygame.display.get_driver()
    window = theme.LOGICAL_SIZE[0] * CAPTURE_SCALE, theme.LOGICAL_SIZE[1] * CAPTURE_SCALE
    notes = f"""# Client screen captures

Regenerated by `pytest tests/client/test_client_screenshots.py`. Do not edit by hand.

| Capture | Screen |
| --- | --- |
| `01-main-menu.png` | Main menu |
| `02-stage-select.png` | Bundled stage selection, with a live terrain preview |
| `03-controls.png` | Controls reference |
| `04-stage-and-hud.png` | Classic stage 1 after {STAGE_TICKS} ticks of held movement and fire |
| `05-pause.png` | Pause menu over the same run |
| `06-run-over-TEST-FIXTURE.png` | Terminal screen from an **injected** simulation state |

## How they were taken

| | |
| --- | --- |
| Logical frame | {theme.LOGICAL_SIZE[0]}x{theme.LOGICAL_SIZE[1]} |
| Capture scale | {CAPTURE_SCALE}x (image is {window[0]}x{window[1]}) |
| SDL video driver | `{driver}` (`SDL_VIDEODRIVER=dummy`) |
| SDL audio driver | `dummy`; the client never initialises audio |
| Input device | Keyboard only. Intents are supplied directly, as the key tables map them |
| pygame-ce | {pygame.version.ver}, SDL {".".join(str(part) for part in pygame.version.SDL)} |
| Python | {platform.python_version()} on {sys.platform} |
| Tile size | {DEFAULT_RULES.tile_size} px, from `battle_city_sim.DEFAULT_RULES` |
| Seed | {shell_seed()} |

## The fixture capture

`06-run-over-TEST-FIXTURE.png` shows a state the test assembled: the run was advanced for
real and then stamped with `BASE_DESTROYED`, together with the matching base damage. No
live run can reach a terminal outcome in this build, because it ships no enemy behaviour
and both outcomes the simulation defines need a hostile projectile. The client only ever
reads an outcome; it never sets one. Enemy waves and stage victory arrive with the AI and
campaign phases.
"""
    path = SCREENSHOT_DIR / "README.md"
    path.write_text(notes, encoding="utf-8")
    written = path.read_text(encoding="utf-8")
    assert "TEST-FIXTURE" in written
    assert "injected" in written.lower()


def shell_seed() -> int:
    """The seed every capture was taken at."""
    return make_shell().seed


def test_every_capture_is_present_and_reasonably_sized() -> None:
    """A capture that grew past a few hundred kilobytes is an artifact problem."""
    captures = sorted(SCREENSHOT_DIR.glob("*.png"))
    assert [path.name for path in captures] == [
        "01-main-menu.png",
        "02-stage-select.png",
        "03-controls.png",
        "04-stage-and-hud.png",
        "05-pause.png",
        "06-run-over-TEST-FIXTURE.png",
    ]
    for path in captures:
        assert 0 < path.stat().st_size < 256 * 1024, path.name


def test_the_capture_directory_is_where_it_is_expected() -> None:
    assert Path(__file__).parent / "screenshots" == SCREENSHOT_DIR
